### ISSUE TITLE
1.19.4 crash when opening Options menu

### ISSUE THREAD

**Issue by Boy0000** [ASangarin/AriKeys#7]
```
Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IncompatibleClassChangeError: Expecting non-static method 'void net.minecraft.class_332.method_25302(net.minecraft.class_4587, int, int, int, int, int, int)'
	at eu.asangarin.arikeys.screen.AriKeysButton.renderButton(AriKeysButton.java:61)
	at eu.asangarin.arikeys.screen.AriKeysButton.method_25394(AriKeysButton.java:42)
	at net.minecraft.class_437.method_25394(class_437.java:131)
	at net.minecraft.class_429.method_25394(class_429.java:149)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:937)
	... 6 more
	```

**Comment by ASangarin** [comment]
AriKeys isn't supported on 1.19.4 yet, please be patient
